mysql-jpa-connections:
  configurations:
    apss:
      jdbc:
        jdbcUrl: jdbc:mysql://data-blume-perfdb-3.rez1.com:3306/stackoptimizer?serverTimezone=UTC&useLegacyDatetimeCode=false
        username: stackappusr
        password: St@cK@pP^$r517
