port: ":7230"
config_port: "7230"

jwt:
  url: 'http://authorization-server.test:7089/jwt/verify'

SQLALCHEMY_APPOINTMENT_URI: "mysql+pymysql://appoiappusr:54u2:V@[MKWS*xY@data-blume-qadb-4.rez1.com:3306/appointmentscheduling"
SQLALCHEMY_STACK_OPTIMIZER_URI: "mysql+pymysql://stackappusr:St%40cK%40pP^$r517@data-blume-qadb-4.rez1.com:3306/stackoptimizer"