server:
  port: 8080
web-proxy:
  configurations:
    mbe:
      path: /mbe-api/*
      forwardUrl: https://dev-apps.blumesolutions.com/mbe-api
    location:
      path: /location-v2-api/*
      forwardUrl: https://dev-apps.blumesolutions.com/location-v2-api

core:
  logger:
    enabled: true
